---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 1h
  values:
    controllers:
      jellyfin:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.6@sha256:25db4eb10143c1c12adb79ed978e31d94fc98dc499fbae2d38b2c935089ced3e
            env:
              TZ: Europe/London
              JELLYFIN_PublishedServerUrl: https://jellyfin.hera.ac
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
              limits:
                memory: 16Gi
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: jellyfin
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        supplementalGroups: [988]
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.69.128
        externalTrafficPolicy: Local
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 401"]
        hostnames:
          - "{{ .Release.Name }}.hera.ac"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: expanse.internal
        path: /var/nfs/shared/Media
        globalMounts:
          - path: /media
            readOnly: true
      tmp:
        type: emptyDir
