---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-auth-secret
    template:
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .GRAFANA_OIDC_CLIENT_ID }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OIDC_CLIENT_SECRET }}"
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: "{{ .GRAFANA_OIDC_AUTH_URL }}"
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "{{ .GRAFANA_OIDC_TOKEN_URL }}"
        GF_AUTH_GENERIC_OAUTH_API_URL: "{{ .GRAFANA_OIDC_API_URL }}"
  dataFrom:
    - extract:
        key: grafana
