---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  chartRef:
    kind: OCIRepository
    name: prowlarr
  interval: 1h
  values:
    controllers:
      prowlarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.6.2.5562@sha256:13c576d2ad93764ab78d4e75c80447bc5489a06a15fd39e89c0be0be01e2ba3a
            env:
              PROWLARR__APP__INSTANCENAME: Prowlarr
              PROWLARR__APP__THEME: dark
              PROWLARR__AUTH__METHOD: External
              PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses
              PROWLARR__LOG__DBENABLED: "False"
              PROWLARR__LOG__LEVEL: info
              PROWLARR__SERVER__PORT: &port 80
              PROWLARR__UPDATE__BRANCH: develop
              TZ: Europe/London
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1Gi
          byparr:
            image:
              repository: ghcr.io/thephaseless/byparr
              tag: 3.0.4@sha256:874f719518f617d03a60e03411fc5d090647e1a877041e81f8dc965927c7deb6
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &byparrPort 8191
                  initialDelaySeconds: 60
                  periodSeconds: 15
                  timeoutSeconds: 60
                  failureThreshold: 40
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *byparrPort
                  periodSeconds: 900
                  timeoutSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *byparrPort
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 3
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                cpu: 2000m
                memory: 3Gi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "vpn",
            "namespace": "kube-system",
            "ips": ["192.168.30.14/24"]
          }]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    podLabels:
      vpn: "true"
    service:
      app:
        ports:
          http:
            port: *port
          byparr:
            port: *byparrPort
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            path: /ping
        hostnames:
          - "{{ .Release.Name }}.hera.ac"
        parentRefs:
          - name: envoy-protected
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      tmp:
        type: emptyDir
        advancedMounts:
          prowlarr:
            app:
              - path: /tmp
