---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-k8s-stack
  interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: flux-metrics-configmap
      valuesKey: flux-metrics.yaml
  values:
    fullnameOverride: vmks
    defaultRules:
      groups:
        etcd:
          create: false
    kubeEtcd:
      enabled: false
    kubeControllerManager:
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                insecureSkipVerify: true
    kubeScheduler:
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                insecureSkipVerify: true
    kubeProxy:
      enabled: false
    prometheus-node-exporter:
      fullnameOverride: node-exporter
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
    grafana:
      enabled: false
    defaultDashboards:
      enabled: false
    experimentalDashboardsEnabled: false
    defaultDatasources:
      enabled: false
    alertmanager:
      route:
        enabled: true
        hostnames:
          - alertmanager.hera.ac
        parentRefs:
          - name: envoy-protected
            namespace: network
      spec:
        disableNamespaceMatcher: true
        externalURL: https://alertmanager.hera.ac
        replicaCount: 1
    vmsingle:
      route:
        enabled: true
        hostnames:
          - prometheus.hera.ac
        parentRefs:
          - name: envoy-protected
            namespace: network
      spec:
        retentionPeriod: 14d
        storage:
          storageClassName: ceph-block
          resources:
            requests:
              storage: 50Gi
