---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notifiarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: notifiarr-secret
    template:
      data:
        DN_API_KEY: '{{ .DN_API_KEY }}'
        DN_SONARR_0_API_KEY: '{{ .DN_SONARR_0_API_KEY }}'
        DN_RADARR_0_API_KEY: '{{ .DN_RADARR_0_API_KEY }}'
        DN_PROWLARR_0_API_KEY: '{{ .DN_PROWLARR_0_API_KEY }}'
        DN_SABNZBD_0_API_KEY: '{{ .DN_SABNZBD_0_API_KEY }}'
        DN_QBIT_0_USER: '{{ .DN_QBIT_0_USER }}'
        DN_QBIT_0_PASS: '{{ .DN_QBIT_0_PASS }}'
        DN_UI_PASSWORD: '{{ .NOTIFIARR_USERNAME }}:{{ .NOTIFIARR_PASSWORD }}'
  data:
    - secretKey: DN_API_KEY
      remoteRef:
        key: notifiarr
        property: NOTIFIARR_API_KEY
    - secretKey: NOTIFIARR_USERNAME
      remoteRef:
        key: notifiarr
        property: NOTIFIARR_USERNAME
    - secretKey: NOTIFIARR_PASSWORD
      remoteRef:
        key: notifiarr
        property: NOTIFIARR_PASSWORD
    - secretKey: DN_SONARR_0_API_KEY
      remoteRef:
        key: sonarr
        property: SONARR_API_KEY
    - secretKey: DN_RADARR_0_API_KEY
      remoteRef:
        key: radarr
        property: RADARR_API_KEY
    - secretKey: DN_PROWLARR_0_API_KEY
      remoteRef:
        key: prowlarr
        property: PROWLARR_API_KEY
    - secretKey: DN_SABNZBD_0_API_KEY
      remoteRef:
        key: sabnzbd
        property: SABNZBD_API_KEY
    - secretKey: DN_QBIT_0_USER
      remoteRef:
        key: qbittorrent
        property: QBITTORRENT_USERNAME
    - secretKey: DN_QBIT_0_PASS
      remoteRef:
        key: qbittorrent
        property: QBITTORRENT_PASSWORD
