---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: outline
spec:
  chartRef:
    kind: OCIRepository
    name: outline
  dependsOn:
    - name: postgresql
      namespace: db
    - name: redis
      namespace: db
  interval: 1h
  values:
    controllers:
      outline:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: outlinewiki/outline
              tag: 1.7.1@sha256:361df7040e6f0d7abac768b99f40122197921626a7e69501aabb5fcb496fc1b4
            env:
              TZ: Europe/London
              NODE_ENV: production
              URL: https://docs.hera.ac
              PORT: &port 3000
              FILE_STORAGE: local
              FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
              OIDC_ISSUER_URL: https://id.hera.ac
              OIDC_DISPLAY_NAME: HyperionID
              OIDC_USERNAME_CLAIM: preferred_username
              OIDC_SCOPES: openid profile email
            envFrom:
              - secretRef:
                  name: outline-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /_health
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /_health
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /_health
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 60
            resources:
              requests:
                cpu: 100m
                memory: 384Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - docs.hera.ac
        parentRefs:
          - name: envoy-external
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /var/lib/outline/data
      tmp:
        type: emptyDir
