---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: glance-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: glance-agent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: glance-agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: app
          image: glanceapp/agent:v0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 27973
              hostPort: 27973
              protocol: TCP
          env:
            - name: PORT
              value: "27973"
            - name: HIDE_MOUNTPOINTS_BY_DEFAULT
              value: "true"
            - name: MOUNTPOINTS
              value: /hostfs/var/lib/rook:Rook-Ceph
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: hostfs
              mountPath: /hostfs
              readOnly: true
      volumes:
        - name: hostfs
          hostPath:
            path: /
            type: Directory
