---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmpodscrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: flux-components
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  podMetricsEndpoints:
    - honorLabels: true
      port: http-prom
  selector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - helm-controller
          - source-controller
          - kustomize-controller
          - notification-controller
