---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dynacat
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dynacat-secret
    template:
      data:
        WEATHER_LOCATION: "{{ .WEATHER_LOCATION }}"
        AUTH_SECRET_KEY: "{{ .AUTH_SECRET_KEY }}"
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        CHANGE_DETECTION_API_KEY: "{{ .CHANGE_DETECTION_API_KEY }}"
        JELLYFIN_API_KEY: "{{ .JELLYFIN_API_KEY }}"
        PIHOLE_APP_PASSWORD: "{{ .PIHOLE_APP_PASSWORD }}"
        QBITTORRENT_USERNAME: "{{ .QBITTORRENT_USERNAME }}"
        QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}"
  data:
    - secretKey: WEATHER_LOCATION
      remoteRef:
        key: dynacat
        property: WEATHER_LOCATION
    - secretKey: AUTH_SECRET_KEY
      remoteRef:
        key: dynacat
        property: AUTH_SECRET_KEY
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: dynacat
        property: OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: dynacat
        property: OIDC_CLIENT_SECRET
    - secretKey: CHANGE_DETECTION_API_KEY
      remoteRef:
        key: change-detection
        property: CHANGE_DETECTION_API_KEY
    - secretKey: JELLYFIN_API_KEY
      remoteRef:
        key: jellyfin
        property: JELLYFIN_API_TOKEN
    - secretKey: PIHOLE_APP_PASSWORD
      remoteRef:
        key: dynacat
        property: PIHOLE_APP_PASSWORD
    - secretKey: QBITTORRENT_USERNAME
      remoteRef:
        key: qbittorrent
        property: QBITTORRENT_USERNAME
    - secretKey: QBITTORRENT_PASSWORD
      remoteRef:
        key: qbittorrent
        property: QBITTORRENT_PASSWORD
