server_url: https://hs.hera.ac
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090

private_key_path: /var/lib/headscale/private.key
noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
  allocation: sequential

dns:
  magic_dns: true
  base_domain: tail.hera.ac
  override_local_dns: false
  nameservers:
    global:
      - 192.168.20.1
    split:
      hera.ac:
        - 192.168.20.1

derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  auto_update_enabled: true
  update_frequency: 24h

database:
  type: sqlite
  sqlite:
    path: /var/lib/headscale/db.sqlite

oidc:
  only_start_if_oidc_is_available: true
  issuer: https://id.hera.ac
  client_id: headscale
  client_secret_path: /etc/headscale/secrets/oidc-client-secret
  pkce:
    enabled: true
  scope: ["openid", "profile", "email", "groups"]
  email_verified_required: false

policy:
  mode: file
  path: /etc/headscale/acl.hujson

log:
  level: info
  format: text
