# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kometa-secret
    template:
      data:
        KOMETA_MDBLISTAPIKEY: '{{ index . "MDBLIST_API_KEY" }}'
        KOMETA_PLEXTOKEN: '{{ index . "PLEX_API_TOKEN" }}'
        KOMETA_RADARRTOKEN: '{{ index . "RADARR_API_KEY" }}'
        KOMETA_SONARRTOKEN: '{{ index . "SONARR_API_KEY" }}'
        KOMETA_TAUTULLIAPIKEY: '{{ index . "TAUTULLI_API_KEY" }}'
        KOMETA_TMDBAPIKEY: '{{ index . "TMDB_API_KEY" }}'
  dataFrom:
    - extract:
        key: plex
    - extract:
        key: kometa
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: tautulli
