---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
spec:
  chartRef:
    kind: OCIRepository
    name: headscale
  interval: 1h
  values:
    controllers:
      headscale:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: headscale/headscale
              tag: v0.28.0@sha256:51b1b9182bb6219e97374fa89af6b9320d6f87ecc739e328d5357ea4fa7a5ce3
            command: ["headscale", "serve"]
            env:
              TZ: Europe/London
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &httpPort 8080
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 12
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *httpPort
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *httpPort
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 1000m
                memory: 512Mi
    service:
      app:
        ports:
          http:
            port: *httpPort
          metrics:
            port: &metricsPort 9090
    serviceMonitor:
      app:
        endpoints:
          - port: metrics
    route:
      app:
        hostnames:
          - hs.hera.ac
        parentRefs:
          - name: envoy-external
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /var/lib/headscale
      config-file:
        type: configMap
        name: "{{ .Release.Name }}-configmap"
        globalMounts:
          - path: /etc/headscale/config.yaml
            subPath: config.yaml
          - path: /etc/headscale/acl.hujson
            subPath: acl.hujson
