---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmprobe_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: lan-icmp
spec:
  module: icmp
  vmProberSpec:
    url: blackbox-exporter-lan.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      targets:
        - expanse.internal
        - hyperion-0.internal
        - hyperion-1.internal
        - hyperion-2.internal
  metricRelabelConfigs:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmprobe_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: lan-tcp
spec:
  module: tcp_connect
  vmProberSpec:
    url: blackbox-exporter-lan.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      targets:
        - expanse.internal:2049
  metricRelabelConfigs:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
