---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: postgresql-secret
    template:
      data:
        password: "{{ .POSTGRES_OUTLINE_PASSWORD }}"
        postgres-password: "{{ .POSTGRES_ADMIN_PASSWORD }}"
        POSTGRES_ADMIN_PASSWORD: "{{ .POSTGRES_ADMIN_PASSWORD }}"
        POSTGRES_OUTLINE_PASSWORD: "{{ .POSTGRES_OUTLINE_PASSWORD }}"
        POSTGRES_AUTOBRR_PASSWORD: "{{ .POSTGRES_AUTOBRR_PASSWORD }}"
        POSTGRES_DASHBRR_PASSWORD: "{{ .POSTGRES_DASHBRR_PASSWORD }}"
        POSTGRES_MEALIE_PASSWORD: "{{ .POSTGRES_MEALIE_PASSWORD }}"
        POSTGRES_POCKET_ID_PASSWORD: "{{ .POSTGRES_POCKET_ID_PASSWORD }}"
        POSTGRES_QUI_PASSWORD: "{{ .POSTGRES_QUI_PASSWORD }}"
        POSTGRES_SEERR_PASSWORD: "{{ .POSTGRES_SEERR_PASSWORD }}"
  dataFrom:
    - extract:
        key: postgresql
