---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: seerr-secret
    template:
      data:
        DB_TYPE: postgres
        DB_HOST: postgresql.db.svc.cluster.local
        DB_PORT: "5432"
        DB_USER: seerr
        DB_PASS: "{{ .POSTGRES_PASSWORD }}"
        DB_NAME: seerr
        DB_USE_SSL: "false"
  dataFrom:
    - extract:
        key: postgresql
