---
alerting:
  pushover:
    application-token: ${STATUS_PUSHOVER_TOKEN}
    default-alert:
      description: health-check failed
      failure-threshold: 3
      minimum-reminder-interval: 1h
      send-on-resolved: true
      success-threshold: 2
    priority: 1
    resolved-priority: 0
    title: Gatus
    user-key: ${STATUS_PUSHOVER_USER_KEY}

endpoints:
  - name: Ping
    group: status
    url: tcp://${STATUS_DDNS_HOSTNAME}:443
    interval: 1m
    ui:
      hide-url: true
      hide-hostname: true
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover

  - name: Status Page
    group: status
    url: https://${STATUS_PAGE_HOSTNAME}
    interval: 1m
    ui:
      hide-url: true
      hide-hostname: true
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
