---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qui-secret
    template:
      data:
        QUI__SESSION_SECRET: "{{ .QUI_SESSION_SECRET }}"
        QUI__OIDC_CLIENT_ID: "{{ .QUI_OIDC_CLIENT_ID }}"
        QUI__OIDC_CLIENT_SECRET: "{{ .QUI_OIDC_CLIENT_SECRET }}"
        QUI__DATABASE_ENGINE: postgres
        QUI__DATABASE_DSN: "postgres://qui:{{ .POSTGRES_QUI_PASSWORD | urlquery }}@postgresql.db.svc.cluster.local:5432/qui?sslmode=disable"
  dataFrom:
    - extract:
        key: postgresql
    - extract:
        key: qui
