---
default_config:

homeassistant:
  latitude: !env_var HASS_LATITUDE
  longitude: !env_var HASS_LONGITUDE
  elevation: !env_var HASS_ELEVATION
  time_zone: Europe/London

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/16

auth_oidc:
  client_id: !env_var HASS_AUTH_OIDC_CLIENT_ID
  client_secret: !env_var HASS_AUTH_OIDC_CLIENT_SECRET ""
  discovery_url: !env_var HASS_AUTH_OIDC_DISCOVERY_URL
  display_name: HyperionID
  roles:
    admin: cluster_admin

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
