---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mealie-secret
    template:
      data:
        OIDC_CLIENT_ID: "{{ .MEALIE_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .MEALIE_OIDC_CLIENT_SECRET }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY | default \"\" }}"
        POSTGRES_USER: mealie
        POSTGRES_PASSWORD: "{{ .POSTGRES_MEALIE_PASSWORD }}"
        POSTGRES_SERVER: postgresql.db.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DB: mealie
  dataFrom:
    - extract:
        key: postgresql
    - extract:
        key: mealie
