---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sportarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sportarr-secret
    template:
      data:
        Sportarr__ApiKey: "{{ .SPORTARR_API_KEY }}"
        Sportarr__Database__Provider: postgres
        Sportarr__Database__Host: postgresql.db.svc.cluster.local
        Sportarr__Database__Port: "5432"
        Sportarr__Database__Name: sportarr
        Sportarr__Database__Username: sportarr
        Sportarr__Database__Password: "{{ .POSTGRES_SPORTARR_PASSWORD }}"
  dataFrom:
    - extract:
        key: postgresql
    - extract:
        key: sportarr
