---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: frigate-secret
    template:
      data:
        FRIGATE_RTSP_USER: "{{ .FRIGATE_RTSP_USER }}"
        FRIGATE_RTSP_PASSWORD: "{{ .FRIGATE_RTSP_PASSWORD }}"
        FRIGATE_MQTT_PASSWORD: "{{ .FRIGATE_MQTT_PASSWORD }}"
        client-secret: "{{ .ENVOY_FRIGATE_OIDC_CLIENT_SECRET }}"
        client-id: "{{ .ENVOY_FRIGATE_OIDC_CLIENT_ID }}"
  dataFrom:
    - extract:
        key: frigate
