---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: frigate-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: frigate
  oidc:
    provider:
      issuer: https://id.hera.ac
    clientIDRef:
      name: frigate-secret
    clientSecret:
      name: frigate-secret
    redirectURL: https://frigate.hera.ac/oauth2/callback
    logoutPath: /logout
    cookieDomain: hera.ac
    scopes:
      - openid
      - profile
      - email
      - groups
    cookieNames:
      accessToken: frigate-access-token
    forwardAccessToken: true
  jwt:
    providers:
      - name: pocket-id
        issuer: https://id.hera.ac
        remoteJWKS:
          uri: https://id.hera.ac/.well-known/jwks.json
        extractFrom:
          cookies:
            - frigate-access-token
        claimToHeaders:
          - header: Remote-User
            claim: preferred_username
          - header: Remote-Groups
            claim: groups
