---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: redis-secret
    template:
      data:
        redis-password: "{{ .REDIS_PASSWORD }}"
  dataFrom:
    - extract:
        key: redis
