---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  chartRef:
    kind: OCIRepository
    name: redis
  interval: 1h
  values:
    architecture: standalone
    commonConfiguration: |-
      appendonly yes
      appendfsync everysec
    auth:
      enabled: true
      existingSecret: redis-secret
      existingSecretPasswordKey: redis-password
    master:
      persistence:
        enabled: true
        storageClass: ceph-block
        size: 1Gi
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          memory: 256Mi
