---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-router
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: headscale
      namespace: network
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/network/tailscale-router/app
  postBuild:
    substitute:
      APP: tailscale-router
      VOLSYNC_CAPACITY: 250Mi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  wait: false
